version: '3.8'

services:
  # Serviço principal da API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - ENVIRONMENT=docker
      - BROWSER_HEADLESS=true
      - BROWSER_DISABLE_SECURITY=true
      - BROWSER_WIDTH=1280
      - BROWSER_HEIGHT=720
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - STORAGE_BASE_PATH=/app/data
    depends_on:
      - rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Serviço RabbitMQ para gerenciamento de filas
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Porta AMQP
      - "15672:15672" # Interface de gerenciamento
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  rabbitmq_data: 